name: geocar
description: "A new Flutter project for workshop geolocation."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0 # <-- AQUÍ ESTÁ LA NUEVA LIBRERÍA DE DISEÑO

  # --- Dependencias TestingCode (Sprint 0) ---
  # Backend y Base de Datos (Firebase)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Geolocalización y Mapas
  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.2

  # Utilidades UI
  shared_preferences: ^2.5.5 # Para guardar sesiones offline
  url_launcher: ^6.3.2
  flutter_polyline_points: ^3.1.0
  image_picker: ^1.2.2
  firebase_storage: ^12.4.10
  flutter_tts: ^4.2.5
  http: ^1.6.0
  firebase_messaging: ^15.2.10
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true